name: LunaStock
version: '${project.version}'
main: kr.lunaf.lunastock.LunaStock
api-version: 1.21
commands:
  주식:
    description: 주식을 사고팔 수 있는 명령어입니다.
    usage: /주식 <buy|sell|list|info|history|returns> <stock_name> [amount]
